# Service for calculating Return on Investment (ROI) for equipment
module Financial
  class RoiCalculator
    attr_reader :product

    def initialize(product:)
      @product = product
    end

    # Calculate comprehensive ROI metrics
    def calculate
      {
        product_id: product.id,
        product_name: product.name,
        purchase_info: purchase_info,
        revenue_metrics: revenue_metrics,
        cost_metrics: cost_metrics,
        roi_metrics: roi_metrics,
        utilization_metrics: utilization_metrics,
        performance_indicators: performance_indicators
      }
    end

    private

    def purchase_info
      {
        purchase_price: product.purchase_price_cents || 0,
        purchase_price_formatted: product.purchase_price&.format || '$0.00',
        purchase_date: product.purchase_date,
        days_owned: days_owned,
        current_value: current_value,
        current_value_formatted: Money.new(current_value, 'USD').format
      }
    end

    def revenue_metrics
      total_revenue = accumulated_revenue

      {
        total_revenue: total_revenue,
        total_revenue_formatted: Money.new(total_revenue, 'USD').format,
        revenue_per_day_owned: revenue_per_day_owned,
        revenue_per_day_owned_formatted: Money.new(revenue_per_day_owned, 'USD').format,
        average_daily_rate: average_daily_rate,
        average_daily_rate_formatted: Money.new(average_daily_rate, 'USD').format
      }
    end

    def cost_metrics
      maintenance_cost = accumulated_maintenance_cost
      depreciation = accumulated_depreciation

      {
        maintenance_cost: maintenance_cost,
        maintenance_cost_formatted: Money.new(maintenance_cost, 'USD').format,
        depreciation: depreciation,
        depreciation_formatted: Money.new(depreciation, 'USD').format,
        total_cost: maintenance_cost + depreciation,
        total_cost_formatted: Money.new(maintenance_cost + depreciation, 'USD').format
      }
    end

    def roi_metrics
      purchase_price = product.purchase_price_cents || 0
      total_revenue = accumulated_revenue
      total_costs = accumulated_maintenance_cost + accumulated_depreciation
      net_profit = total_revenue - total_costs

      roi_percentage = if purchase_price.zero?
        0
      else
        (net_profit.to_f / purchase_price * 100).round(2)
      end

      {
        net_profit: net_profit,
        net_profit_formatted: Money.new(net_profit, 'USD').format,
        roi_percentage: roi_percentage,
        payback_period_months: payback_period_months,
        break_even_status: break_even_status(net_profit, purchase_price)
      }
    end

    def utilization_metrics
      {
        total_days_rented: days_rented,
        utilization_rate: product.utilization_rate || 0,
        rental_frequency: rental_frequency
      }
    end

    def performance_indicators
      {
        is_profitable: is_profitable?,
        is_underperforming: is_underperforming?,
        high_maintenance: high_maintenance?,
        recommendation: recommendation
      }
    end

    # Helper methods
    def days_owned
      return 0 unless product.purchase_date
      (Date.current - product.purchase_date).to_i
    end

    def accumulated_revenue
      # Sum of all revenue generated by this product
      if product.respond_to?(:accumulated_revenue_cents) && product.accumulated_revenue_cents
        product.accumulated_revenue_cents
      else
        BookingLineItem.where(bookable: product)
                       .joins(:booking)
                       .where('bookings.status IN (?)', [Booking.statuses[:confirmed], Booking.statuses[:in_progress], Booking.statuses[:completed]])
                       .sum(:line_total_cents)
      end
    end

    def accumulated_maintenance_cost
      # Sum of all maintenance costs
      if product.respond_to?(:accumulated_maintenance_cost_cents) && product.accumulated_maintenance_cost_cents
        product.accumulated_maintenance_cost_cents
      elsif defined?(MaintenanceJob)
        MaintenanceJob.where(product: product)
                      .where(status: :completed)
                      .sum(:total_cost_cents)
      else
        0
      end
    end

    def accumulated_depreciation
      # Calculate total depreciation since purchase
      return 0 unless product.purchase_date
      product.accumulated_depreciation
    end

    def current_value
      purchase_price = product.purchase_price_cents || 0
      depreciation = accumulated_depreciation
      [purchase_price - depreciation, 0].max
    end

    def revenue_per_day_owned
      return 0 if days_owned.zero?
      (accumulated_revenue.to_f / days_owned).round(0)
    end

    def average_daily_rate
      return 0 if days_rented.zero?
      (accumulated_revenue.to_f / days_rented).round(0)
    end

    def days_rented
      # Total number of rental days
      BookingLineItem.where(bookable: product)
                     .joins(:booking)
                     .where('bookings.status IN (?)', [Booking.statuses[:confirmed], Booking.statuses[:in_progress], Booking.statuses[:completed]])
                     .sum(:days)
    end

    def rental_frequency
      # Average days between rentals
      return 0 if days_owned.zero? || days_rented.zero?
      (days_owned.to_f / rental_count).round(1)
    end

    def rental_count
      BookingLineItem.where(bookable: product)
                     .joins(:booking)
                     .where('bookings.status IN (?)', [Booking.statuses[:confirmed], Booking.statuses[:in_progress], Booking.statuses[:completed]])
                     .count
    end

    def payback_period_months
      purchase_price = product.purchase_price_cents || 0
      return 0 if purchase_price.zero?

      monthly_revenue = if days_owned >= 30
        (accumulated_revenue.to_f / days_owned * 30).round(0)
      else
        0
      end

      return nil if monthly_revenue.zero?
      (purchase_price.to_f / monthly_revenue).round(1)
    end

    def break_even_status(net_profit, purchase_price)
      if net_profit >= purchase_price
        'profitable'
      elsif net_profit >= 0
        'break_even'
      else
        'losing_money'
      end
    end

    def is_profitable?
      net_profit = accumulated_revenue - accumulated_maintenance_cost - accumulated_depreciation
      purchase_price = product.purchase_price_cents || 0
      net_profit >= purchase_price
    end

    def is_underperforming?
      # ROI < 0% after 1 year OR utilization < 20%
      return false if days_owned < 365

      roi = calculate_roi_percentage
      utilization = product.utilization_rate || 0

      roi < 0 || utilization < 20
    end

    def high_maintenance?
      # Maintenance cost > 30% of revenue
      return false if accumulated_revenue.zero?
      (accumulated_maintenance_cost.to_f / accumulated_revenue * 100) > 30
    end

    def calculate_roi_percentage
      purchase_price = product.purchase_price_cents || 0
      return 0 if purchase_price.zero?

      net_profit = accumulated_revenue - accumulated_maintenance_cost - accumulated_depreciation
      (net_profit.to_f / purchase_price * 100).round(2)
    end

    def recommendation
      return 'insufficient_data' if days_owned < 90

      if is_profitable?
        'keep_renting'
      elsif is_underperforming? && high_maintenance?
        'consider_selling'
      elsif is_underperforming?
        'increase_marketing'
      elsif high_maintenance?
        'reduce_maintenance_frequency'
      else
        'monitor_performance'
      end
    end
  end
end
